<script setup>
import { computed, ref, watch } from 'vue'
import { useThreeScene } from '../../composables/useThreeScene'
import SceneTooltip from './SceneTooltip.vue'

const props = defineProps({ orders: { type: Array, default: () => [] }, connected: Boolean, reducedMotion: Boolean })
const modes = ['订单流', '区域', '品类', '异常']
const mode = ref('订单流')
const selectedRegion = ref(null)
const tip = ref({ visible: false, x: 0, y: 0, title: '', rows: [] })
const regionPositions = { 华东: [4.8, .6, 0], 华南: [2.1, .6, 4.2], 华北: [-3.8, .6, 2.9], 西南: [-4.3, .6, -2.3], 海外: [2.5, .6, -4.1] }
const regionStats = computed(() => Object.keys(regionPositions).map((region) => { const list = props.orders.filter((o) => o.region === region); const products = {}; list.forEach((o) => { products[o.product] = (products[o.product] || 0) + 1 }); return { region, count: list.length, gmv: list.reduce((sum, o) => sum + o.amount, 0), anomalies: list.filter((o) => o.is_anomaly).length, product: Object.entries(products).sort((a, b) => b[1] - a[1])[0]?.[0] || '暂无', latest: list[0]?.order_code || '暂无' } }))
const selected = computed(() => regionStats.value.find((item) => item.region === selectedRegion.value))

const { host, ready, error, paused, context, resetCamera } = useThreeScene({
  cameraPosition: [10, 9, 13], target: [0, .5, 0],
  setup({ THREE, scene, camera, renderer, controls }) {
    const grid = new THREE.GridHelper(26, 26, 0x21405f, 0x11283d); grid.material.transparent = true; grid.material.opacity = .4; scene.add(grid)
    const core = new THREE.Group(); const coreBase = new THREE.Mesh(new THREE.CylinderGeometry(1.3, 1.7, .35, 40), new THREE.MeshStandardMaterial({ color: 0x16364e, metalness: .7, roughness: .25 })); const coreOrb = new THREE.Mesh(new THREE.OctahedronGeometry(.85, 2), new THREE.MeshStandardMaterial({ color: 0x50c8e8, emissive: 0x145e72, emissiveIntensity: 1.5, metalness: .25, roughness: .2 })); coreOrb.position.y = 1.15; const coreRing = new THREE.Mesh(new THREE.TorusGeometry(1.35, .025, 8, 64), new THREE.MeshBasicMaterial({ color: 0x7367f0, transparent: true, opacity: .7 })); coreRing.rotation.x = Math.PI / 2; coreRing.position.y = .25; core.add(coreBase, coreOrb, coreRing); scene.add(core)
    const regionMeshes = {}; const interactives = []
    Object.entries(regionPositions).forEach(([region, position]) => { const group = new THREE.Group(); group.position.set(...position); group.userData.region = region; const pad = new THREE.Mesh(new THREE.CylinderGeometry(.72, .9, .22, 24), new THREE.MeshStandardMaterial({ color: 0x18334b, metalness: .55, roughness: .35 })); const beacon = new THREE.Mesh(new THREE.CylinderGeometry(.12, .35, 1, 16), new THREE.MeshStandardMaterial({ color: 0x34d399, emissive: 0x0c5b48, emissiveIntensity: 1.1 })); beacon.position.y = .58; beacon.userData.region = region; interactives.push(beacon); group.add(pad, beacon); scene.add(group); regionMeshes[region] = { group, beacon } })
    const categoryGroup = new THREE.Group(); scene.add(categoryGroup); const orderGroup = new THREE.Group(); scene.add(orderGroup); const orderObjects = new Map()
    const update = (orders) => {
      const stats = {}; orders.forEach((o) => { (stats[o.region] ||= []).push(o) })
      Object.entries(regionMeshes).forEach(([region, item]) => { const list = stats[region] || [], anomalyRate = list.length ? list.filter((o) => o.is_anomaly).length / list.length : 0; item.beacon.scale.y = .7 + Math.min(1.5, list.length * .18); item.beacon.material.color.setHex(anomalyRate > .25 ? 0xfb7185 : 0x34d399); item.beacon.material.emissive.setHex(anomalyRate > .25 ? 0x7b2230 : 0x0c5b48) })
      const ids = new Set(orders.map((o) => o.order_code)); orderObjects.forEach((object, id) => { if (!ids.has(id)) { object.traverse((o) => { o.geometry?.dispose(); o.material?.dispose() }); orderGroup.remove(object); orderObjects.delete(id) } })
      orders.forEach((order, index) => { if (orderObjects.has(order.order_code) || !regionPositions[order.region]) return; const end = new THREE.Vector3(...regionPositions[order.region]).add(new THREE.Vector3(0, 1.2, 0)); const start = new THREE.Vector3(0, 1.3, 0); const mid = start.clone().add(end).multiplyScalar(.5); mid.y += 2 + index % 3 * .25; const curve = new THREE.QuadraticBezierCurve3(start, mid, end); const color = order.is_anomaly ? 0xfb7185 : 0x50c8e8; const line = new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(32)), new THREE.LineBasicMaterial({ color, transparent: true, opacity: order.is_anomaly ? .8 : .28 })); const particle = new THREE.Mesh(new THREE.SphereGeometry(order.is_anomaly ? .105 : .07, 8, 8), new THREE.MeshBasicMaterial({ color })); const group = new THREE.Group(); group.userData = { order, curve, phase: -index * .04 }; group.add(line, particle); orderGroup.add(group); orderObjects.set(order.order_code, group) })
      while (categoryGroup.children.length) { const item = categoryGroup.children.pop(); item.geometry.dispose(); item.material.dispose() }
      const categories = {}; orders.forEach((o) => { categories[o.category] = (categories[o.category] || 0) + 1 }); Object.entries(categories).forEach(([category, count], index, all) => { const angle = index / all.length * Math.PI * 2; const bar = new THREE.Mesh(new THREE.CylinderGeometry(.22, .3, .35 + count * .25, 12), new THREE.MeshStandardMaterial({ color: 0x7367f0, emissive: 0x2a246d, emissiveIntensity: .8 })); bar.position.set(Math.cos(angle) * 2.6, (.35 + count * .25) / 2, Math.sin(angle) * 2.6); bar.userData.category = category; categoryGroup.add(bar) })
    }
    update(props.orders)
    const raycaster = new THREE.Raycaster(); const pointer = new THREE.Vector2(); let last = 0
    const pick = (event, click = false) => { if (!click && performance.now() - last < 50) return; last = performance.now(); const rect = renderer.domElement.getBoundingClientRect(); pointer.set((event.clientX - rect.left) / rect.width * 2 - 1, -(event.clientY - rect.top) / rect.height * 2 + 1); raycaster.setFromCamera(pointer, camera); const hit = raycaster.intersectObjects(interactives, false)[0]; renderer.domElement.style.cursor = hit ? 'pointer' : 'grab'; if (!hit) { tip.value.visible = false; if (click) selectedRegion.value = null; return } const region = hit.object.userData.region; const data = regionStats.value.find((item) => item.region === region); tip.value = { visible: !click, x: event.clientX - rect.left + 12, y: event.clientY - rect.top + 12, title: region, rows: [['订单', data?.count || 0], ['GMV', '¥' + Number(data?.gmv || 0).toLocaleString()], ['异常', data?.anomalies || 0]] }; if (click) { selectedRegion.value = region; controls.target.copy(hit.object.getWorldPosition(new THREE.Vector3())); controls.update() } }
    const move = (e) => pick(e); const click = (e) => pick(e, true); renderer.domElement.addEventListener('pointermove', move); renderer.domElement.addEventListener('click', click)
    return { core, regionMeshes, orderGroup, categoryGroup, orderObjects, update, animate(delta, elapsed) { coreOrb.rotation.y += delta * .5; coreRing.rotation.z -= delta * .22; if (!props.reducedMotion) coreOrb.position.y = 1.15 + Math.sin(elapsed * 1.5) * .06; orderObjects.forEach((group) => { group.userData.phase = (group.userData.phase + delta * .18) % 1; const particle = group.children[1]; particle.position.copy(group.userData.curve.getPoint(Math.max(0, group.userData.phase))) }) }, dispose() { renderer.domElement.removeEventListener('pointermove', move); renderer.domElement.removeEventListener('click', click) } }
  }
})

watch(() => props.orders, (orders) => context.value?.update(orders), { deep: true })
watch(mode, (value) => { const ctx = context.value; if (!ctx) return; ctx.orderGroup.visible = value === '订单流' || value === '异常'; ctx.categoryGroup.visible = value === '品类'; Object.values(ctx.regionMeshes).forEach((item) => { item.group.visible = value !== '品类' }); ctx.orderObjects.forEach((group) => { group.visible = value !== '异常' || group.userData.order.is_anomaly }) })
</script>

<template><article class="twin-card commerce-twin"><div class="twin-head"><div><span class="scene-kicker">COMMERCE NETWORK</span><h3>实时商业网络</h3><p>抽象业务区域与订单流，不映射真实地理位置</p></div><div class="scene-actions"><button @click="paused = !paused">{{ paused ? '继续动画' : '暂停动画' }}</button><button @click="resetCamera">重置视角</button></div></div><div class="scene-filters"><button v-for="item in modes" :key="item" :class="{ active: mode === item }" @click="mode = item">{{ item }}</button></div><div class="scene-stage"><div ref="host" class="three-host"></div><div v-if="!orders.length" class="scene-empty">暂无订单数据，场景不会生成模拟订单</div><div v-else-if="!ready && !error" class="scene-loading"><i></i>正在连接商业网络…</div><div v-if="error" class="scene-error">WebGL 初始化失败：{{ error }}</div><div v-if="!connected" class="scene-disconnected">数据连接中断 · 保留最后有效状态</div><SceneTooltip v-bind="tip"/><div v-if="selected" class="scene-detail"><button @click="selectedRegion = null">×</button><span>REGION INSPECTOR</span><h4>{{ selected.region }}</h4><div><small>订单数</small><strong>{{ selected.count }}</strong></div><div><small>GMV</small><strong>¥{{ selected.gmv.toLocaleString() }}</strong></div><div><small>异常</small><strong>{{ selected.anomalies }}</strong></div><div><small>主要商品</small><strong>{{ selected.product }}</strong></div><div><small>最新订单</small><strong>{{ selected.latest }}</strong></div></div><div class="scene-help">点击区域查看真实订单聚合 · 弧线代表订单去向</div></div></article></template>
